# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d313991ea0e25da409367dee8351d58170d840fd875335fd2efa9f131a76b785949bf98c7beb96a8f4400033c79325ded8b8ba7bad0128cc3905dbe21699181c

test:
  secret_key_base: 24a88e4f5f1ae0eded4f0dc2c285209e54c85e55c97bbf8b7b5d760bfaf74fb945f87c2ddde8268f740d9460b4aed197dc119bd0a30e148dcf12573fb9463b53

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
